#!/usr/bin/env clojure -Sdeps {:deps,{selmer/selmer,{:mvn/version,"1.12.17"}}}
;; Taken from https://github.com/borkdude/clj-kondo/blob/ca947294b18df2b1049ceca5a29578cee89b037f/script/update-project.clj

(require '[selmer.parser :as p])
(require '[clojure.java.io :as io])
(require '[clojure.string :as str])
(require '[clojure.edn :as edn])

(def version "0.1.0-alpha2")

(def deps-edn (edn/read-string (slurp "deps.edn")))

(def deps-dependencies (:deps deps-edn))
(def lein-dependencies (cons '[org.clojure/clojure "1.9.0"]
                             (map (fn [[k v]]
                                    [k (:mvn/version v)])
                                  deps-dependencies)))

(def deps-test-dependencies (-> deps-edn :aliases :test :extra-deps))
(def lein-test-dependencies (keep (fn [[k v]]
                                    (when-not (#{'cognitect/test-runner 'org.clojure/clojure} k)
                                      [k (:mvn/version v)]))
                                  deps-test-dependencies))

(spit "project.clj" (str ";; GENERATED by script/update-project.clj.template, DO NOT EDIT\n"
                         ";; To change dependencies, update deps.edn and run script/update-project.clj.template.\n"
                         ";; To change other things, edit project.template.clj and run script/update-project.clj.template.\n"
                         "\n"
                         (p/render (slurp (io/file "project.clj.template"))
                                   {:version version
                                    :dependencies
                                             (format "[%s]"
                                                     (str/join "\n                 "
                                                               lein-dependencies))
                                    :test-dependencies
                                             (format "[%s]"
                                                     (str/join "\n                                   "
                                                               lein-test-dependencies))})))
